import {
  AddressPin,
  Adjustments,
  AdjustmentsHorizontal,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownSolid,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  ArrowUpSolid,
  BankOffice,
  BarChart,
  BarChart2,
  Bell,
  Box,
  Calendar,
  Cash,
  CashBanknote,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Columns,
  Company,
  Copy,
  CornerDownLeft,
  CreditCard,
  Directory,
  DollarSign,
  DotCircle,
  Download,
  DownloadCloud,
  Edit,
  Edit2,
  Edit3,
  Equals,
  Eye,
  EyeOff,
  File,
  FileMinus,
  FilePlus,
  Filter,
  Folder,
  Info,
  Jpg,
  LifeBuoy,
  Loader,
  Mail,
  MailOpen,
  Maximize,
  Menu,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Note,
  Package,
  Paperclip2,
  Pdf,
  PenTool,
  PhotoOff,
  Plus,
  PlusCircle,
  Png,
  Printer,
  RightLeftCircuit,
  Search,
  Send,
  Settings,
  ShoppingCart,
  Sliders,
  Square,
  Star,
  StarFull,
  Stock,
  Sun,
  Tag,
  Trash,
  Trash2,
  Upload,
  UploadReceipt,
  User,
  Users,
  X,
  XOctagon,
  XSquare,
  ZoomIn,
  ZoomOut,
} from '../components/icons';

export const CUSTOM_ICON = {
  ADDRESS_PIN: AddressPin,
  ADJUSTMENT: Adjustments,
  ADJUSTMENT_HORIZONTAL: AdjustmentsHorizontal,
  ARCHIVE: Archive,
  ARROW_DOWN: ArrowDown,
  ARROW_DOWN_LEFT: ArrowDownLeft,
  ARROW_DOWN_SOLID: ArrowDownSolid,
  ARROW_LEFT: ArrowLeft,
  ARROW_RIGHT: ArrowRight,
  ARROW_UP: ArrowUp,
  ARROW_UP_RIGHT: ArrowUpRight,
  ARROW_UP_SOLID: ArrowUpSolid,
  BANK_OFFICE: BankOffice,
  BAR_CHART: BarChart,
  BAR_CHART_2: BarChart2,
  BELL: Bell,
  BOX: Box,
  CASH: Cash,
  CASH_BANKNOTE: CashBanknote,
  CALENDAR: Calendar,
  CHECK: Check,
  CHECK_CIRCLE: CheckCircle,
  CHEVRON_DOWN: ChevronDown,
  CHEVRON_LEFT: ChevronLeft,
  CHEVRON_RIGHT: ChevronRight,
  CHEVRON_UP: ChevronUp,
  CIRCLE: Circle,
  CLOCK: Clock,
  CLOSE: X,
  COLUMNS: Columns,
  COMPANY: Company,
  COPY: Copy,
  CORNER_DOWN_LEFT: CornerDownLeft,
  CREDIT_CART: CreditCard,
  DANGER: XOctagon,
  DIRECTORY: Directory,
  DOLLAR_SIGN: DollarSign,
  DOT_CIRCLE: DotCircle,
  DOWNLOAD: Download,
  DOWNLOAD_CLOUD: DownloadCloud,
  EDIT: Edit,
  EDIT_2: Edit2,
  EDIT_3: Edit3,
  EQUALS: Equals,
  EYE: Eye,
  EYE_OFF: EyeOff,
  FILE: File,
  FILE_MINUS: FileMinus,
  FILE_PLUS: FilePlus,
  FILTER: Filter,
  FOLDER: Folder,
  INFO: Info,
  JPG: Jpg,
  LIFE_BUOY: LifeBuoy,
  LOADER: Loader,
  MAIL: Mail,
  MAIL_OPEN: MailOpen,
  MAXIMIZE: Maximize,
  MENU: Menu,
  MINUS: Minus,
  MONITOR: Monitor,
  MOON: Moon,
  MORE_HORIZONTAL: MoreHorizontal,
  MORE_VERTICAL: MoreVertical,
  NOTE: Note,
  PACKAGE: Package,
  PAPERCLIP_2: Paperclip2,
  PDF: Pdf,
  PEN_TOOL: PenTool,
  PLUS: Plus,
  PLUS_CIRCLE: PlusCircle,
  PNG: Png,
  PRINTER: Printer,
  RIGHT_LEFT_CIRCUIT: RightLeftCircuit,
  SEARCH: Search,
  SEND: Send,
  SETTINGS: Settings,
  SLIDERS: Sliders,
  SQUARE: Square,
  SHOPPING_CARD: ShoppingCart,
  STAR: Star,
  STAR_FULL: StarFull,
  STOCK: Stock,
  SUCCESS: Check,
  SUN: Sun,
  TAG: Tag,
  TRASH: Trash,
  TRASH_2: Trash2,
  UPLOAD: Upload,
  UPLOAD_RECEIPT: UploadReceipt,
  USER: User,
  USERS: Users,
  PHOTO_OFF: PhotoOff,
  WARNING: AlertTriangle,
  X,
  X_OCTAGON: XOctagon,
  X_SQUARE: XSquare,
  ZOOM_IN: ZoomIn,
  ZOOM_OUT: ZoomOut,
};
